name: 🔧 Improvement
description: Suggest an improvement to existing functionality in GenForm
title: "[Improvement]: "
labels: ["improvement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! Help us make GenForm better.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what you'd like to improve.
      placeholder: Describe the improvement...
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works.
      placeholder: Currently, when I...
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: Describe how you think it should be improved.
      placeholder: |
        It would be better if...
        - Improvement 1
        - Improvement 2
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this improvement bring?
      placeholder: |
        - Better performance
        - Improved user experience
        - Easier maintenance
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area of Improvement
      description: Which area does this improvement relate to?
      options:
        - UI/UX
        - Performance
        - Accessibility
        - Code Quality
        - Documentation
        - Testing
        - Security
        - Other
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the improvement.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
